### ISSUE TITLE
Add support for coverage runs.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/fuzzing-tc#45]
Coverage runs are pools that run for only one cycle, at a fixed time weekly.

**Comment by jschwartzentruber** [comment]
I think this will work as a mix-in, like this:

#### pool1.yml
```yml
name: pool 1
parents:
 - base
size: 8
env:
   xyz: true
```
#### coverage.yml
```yml
name: coverage
apply_to:
 - pool1
size: 1
env:
  coverage: true
```

This should yield one task per item in `apply_to`, and the result would look like:
```yml
name: pool 1 (coverage)
size: 1
env:
  coverage: true
  xyz: true
```

We will have a problem of worker-pools, as some will have different requirements than others. For now the easy solution is to use the maximum spec of all of the pools listed (max cores/task, max ram/core, union of all privileges and features). This will break down when we support arm64.

**Comment by jschwartzentruber** [comment]
This also requires a couple changes to how we schedule tasks. For coverage, we want:

1. a fixed schedule reference. eg. we want the schedule to run weekly on Sunday night
1. separation of schedule and run time. eg. we want to run for 12 hours every 7 days

To keep this simple, I'm going to require (1) to be a simple datetime string called `schedule_start`.
`cycle_time` will continue to be the period at which tasks are scheduled. (2) will be a new field `max_run_time` which is a period with the same format as `cycle_time`.

So for a weekly 12h job as in the example above starting at midnight Sunday evening, the config should contain:

```yml
schedule_start: 2020-06-15T00:00:00Z
cycle_time: 7d
max_run_time: 12h
```

It may be confusing that the schedule is continuous, and `schedule_start` could be any arbitrary date in the future or past, but this is easier than trying to parse cron fields into a specific time reference.
